---
abstract: 'Regular Expressions Support for Cherokee Script and the Languages that use it.'
author:
  - 'Daniel Yacob <dyacob\@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Regexp-Cherokee
provides:
  Regexp::Cherokee:
    file: lib/Regexp/Cherokee.pm
    version: '0.06'
requires:
  perl: v5.8.0
resources:
  bugtracker: https://github.com/dyacob/Regexp-Cherokee/issues
  homepage: https://github.com/dyacob/Regexp-Cherokee
  license: http://dev.perl.org/licenses/
  repository: https://github.com/dyacob/Regexp-Cherokee.git
version: '0.06'
x_authority: cpan:dyacob
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
